### ISSUE TITLE
Add tenant to all `taxonomy` endpoints

### ISSUE THREAD

**Issue by khyurri** [epam/badgerdoc#109]
Back-end:
- [ ] `/taxonomy/taxonomy/` there is no tenant in header (add tenant dependency)

Description:
1. Every resource in this [module](https://github.com/epam/badgerdoc/blob/main/taxonomy/app/taxonomy/resources.py) requires Tenant to be accepted as a header.
Example is [here](https://github.com/epam/badgerdoc/blob/main/taxonomy/app/taxonomy/resources.py#L54)

2. Every time you make a query to the Taxonomy table in the database, tenant should be validated - compare received external tenant and existed entity's one.
Examples: [1](https://github.com/epam/badgerdoc/blob/main/taxonomy/app/taxon/services.py#L91), [2](https://github.com/epam/badgerdoc/blob/main/taxonomy/app/taxon/services.py#L206)
Examples from the annotation service table Categories - which is also using tenants: [1](https://github.com/epam/badgerdoc/blob/main/annotation/app/categories/services.py#L42), [2](https://github.com/epam/badgerdoc/blob/main/annotation/app/categories/services.py#L224), [3](https://github.com/epam/badgerdoc/blob/main/annotation/app/categories/services.py#L267)

**Comment by andrejshulaev** [comment]
Probably, `models` service should be reworked the same way.
