### ISSUE TITLE
Step ID should be generated as UUID on Pipeline creation

### ISSUE THREAD

**Issue by MagicTearsAsunder** [epam/badgerdoc#126]
While adding new pipeline and setting new steps _http://host/pipelines/add_ badgerdock sends the request:

POST
```
{
    "meta": {
        "type": "preprocessing",
        "name": "my_pipeline_2",
        "categories": [],
        "description": "",
        "summary": ""
    },
    "steps": [
        {
            "version": 1,
            "model": "easy-ocr",
            "id": "EiOONwjvwTVMGYV31jF2D",
            "model_url": "easy-ocr"
        }
    ]
}
```
**"steps" -> "id"** should be either generated as **UUID** format or removed completely since it would be generated on back-end side.

**Comment by iurii-topychkanov** [comment]
Id is actually generated on backend side.
The flow is like that:

- If we are creating totally new pipeline steps property will be steps: []
- If we are creating pipeline from existing one steps property will be taken from existing pipeline, that's why the ID is passed from UI.

**Comment by iurii-topychkanov** [comment]
Id is needed for proper work of pipeline canvas, so it wasn't removed totally instead of this library for ID creation was changed from nanoid to uuid
