### ISSUE TITLE
Document labelling: support of multi-label tagging on document level (e.g. for document classification purposes).

### ISSUE THREAD

**Issue by khyurri** [epam/badgerdoc#13]
Back-end:
- [x] Add labels for each revision, not in manifest level

Design:
- [x] Design how to set tag per document

Front-end:
- [x] Implement

**Comment by Kitonick79** [comment]
This task is about classifying document with multiple labels. We need to get model output, take labels for a document as a whole and display it on UI. We would need some UX support here.

**Comment by MikhailFokanov** [comment]
As we discussed today to save the time and effort, the acceptable and solid workaround is to have a simple category named "bucket". The annotator will draw a rectangle in the free sapce in the top right corner with "free-box" tool and then select the right entity from taxonomy in the data tab (as usual). No changes should be done on UI in such case. On the export process converter can just find the box with bucket category and set it to the document.
Multiple labels are also available out-of-the-box with such approach.

**Comment by Kitonick79** [comment]
> 
But how should it be imported from model's output?

**Comment by MikhailFokanov** [comment]
Nothing should be done on the backend/frontend side, if the proposed solution with box is accepted by customer. Only during the export process converter can just find the box with bucket category and set it to the document.

**Comment by khyurri** [comment]
@MikhailFokanov 
Could you please explain what is box and what is export process? 

This task is about to add users functionality to assign category to whole document. This is exactly same, as assign category to some bbox, but to whole document. 

Please, check PR description, @cakeinsauce  already added API and we wanted to finish from front-end task

**Comment by khyurri** [comment]
FE is required

**Comment by Iogsotot** [comment]
Need to fix BE https://github.com/epam/badgerdoc/issues/128

**Comment by Iogsotot** [comment]
https://github.com/epam/badgerdoc/pull/157 done
