### ISSUE TITLE
Create CI on Github Actions

### ISSUE THREAD

**Issue by khyurri** [epam/badgerdoc#17]
Add GitHub Actions to run CI pipelines for each microservice

# Annotation service 
- [x] run pre-commits on annotation service
- [x] run pytest on annotation service

# Filter-lib
- [x] run pre-commits on Filter-lib
- [x] run pytest on Filter-lib

# Tenants
- [x] run pre-commits on Tenants
- [x] run pytest on Tenants

# Assets
- [x] run pre-commits on Assets
- [x] run pytest on Assets

**Comment by thinklab** [comment]
@thinklab
