### ISSUE TITLE
Taxonomy and Categories: Add loading of next pages when user scrolls

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#176]
For now we send only one request to get the first page. We need to add listeners on scroll to load other pages.

- [ ] Document Labels
- [ ] Taxonomies tree

**Comment by MarinaVorobeva21** [comment]
Taxonomies on Data tab are not loading when there are a lot of categories in the list on the Category tab.

https://user-images.githubusercontent.com/98399603/234328924-57767736-5780-46b3-91ec-4f4d35821135.mp4

**Comment by MarinaVorobeva21** [comment]
Verified
