### ISSUE TITLE
Any category except 'Category' are not displayed on the list in annotation tasks/document views

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#204]
Steps to reproduce: 
1. Create some extraction job with more than one category ()
2. Open the job as annotator, check available categories.

Expected result:
All chosen category are presented in Category list. 

Result:
The only category which can be displayed is 'Category', all other are unavailable. 
![image](https://user-images.githubusercontent.com/80756170/211794388-dcfa0459-1a07-4a2c-813d-b55db53124a6.png)

**Comment by DaryaGurtovenko** [comment]
Closed as fixed
![image](https://user-images.githubusercontent.com/80756170/212048370-a899501e-895a-4769-82b7-33a29b236260.png)

**Comment by iurii-topychkanov** [comment]
There is no problem with categories
