### ISSUE TITLE
500 error when try to create new extraction job during file convert on dev2

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#214]
Steps to reproduce:
1. Login to dev2 as admin
2. In documents tab press 'Upload wizard' button. 
3. Choose .txt doc.
4. Go ahead until job extraction page open.
5. Fill all mandatory fields. 
6. Press 'Start extraction' button.

Expected result:
Job created and file converted.

Result:
500 error appears. The following in dev console:
![image](https://user-images.githubusercontent.com/80756170/212305008-84ef6371-df0f-483b-b685-b2b4fc5e0e41.png)
![image](https://user-images.githubusercontent.com/80756170/212305077-4ce31cbc-8e98-4afe-93cd-4fb43e7970df.png)

It's impossible now to finish file uploading because of that defect.

**Comment by thinklab** [comment]
fixed in #207
