### ISSUE TITLE
Annotation label switches from taxon to category on save

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#221]
Select an annotation which category has taxonomy
Select taxon - annotation label has taxon value
Click Save Draft - Label switched to category
Before save:
![Screenshot 2023-01-17 at 13 07 59](https://user-images.githubusercontent.com/69203629/213104594-e6d0fa09-0d5d-40a6-a778-b501273aec1c.png)
After save:
![Screenshot 2023-01-17 at 13 08 52](https://user-images.githubusercontent.com/69203629/213104626-95164d4b-ebfd-4c6c-b0de-6c1f505bd28e.png)

**Comment by Iogsotot** [comment]
fixed in https://github.com/epam/badgerdoc/pull/242
