### ISSUE TITLE
Issues with taxonomy tree

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#222]
Create an annotation using category with taxonomy: Data tab opened and taxon tree showed
1. There should be 'closed" tree, only root categories should be shown
2. Taxon tree doesn't have open-close arrows for non-leaf nodes
3. When clicking on arrow - child nodes should be loaded
4. Node titles are cut
![Screenshot 2023-01-17 at 13 05 29](https://user-images.githubusercontent.com/69203629/213104389-b7a2b08b-ca9d-43ae-a90d-1fd39cfeae93.png)

**Comment by Iogsotot** [comment]
fixed https://github.com/epam/badgerdoc/pull/269

**Comment by Iogsotot** [comment]
@DaryaGurtovenko pls check (when env is ready)

**Comment by MarinaVorobeva21** [comment]
Fixed
