### ISSUE TITLE
Dialog window doesn’t close automatically after validation is finished

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#225]
_Issue came from UAT_

**Preconditions:**
An extraction job is created, all annotation tasks within it are finished.

**Steps**
1. Open validation task as assigned user
2. Select “Valid” in the bottom of panel with labels
3. Click “Finish validation” button. A dialog window appears
![image](https://user-images.githubusercontent.com/80756170/213176501-77f24473-7549-4b70-803a-7c17668f58c1.png)
4. Click “Confirm validation and assignment” button

Result:
The window remains open, status of the validation task remains “Ready".

Front-end:
- [ ] clarify in what cases `0` is shown in this window instead of form field

**Comment by khyurri** [comment]
This bug is related to: #190 , but in case of back-end error, this window will not close to allow users resend form

**Comment by Andrka** [comment]
Validation is completed after saving the draft and then completing the validation. Maybe UI problems
![2023-01-24_17-29](https://user-images.githubusercontent.com/14347940/214308937-82e7d2f6-9884-49d7-8def-d74b0a628bc1.png)
'0' is not displayed

**Comment by MarinaVorobeva21** [comment]
Still reproduces

**Comment by Annaburnazyan** [comment]
Fixed.

**Comment by MarinaVorobeva21** [comment]
Fixed
