### ISSUE TITLE
Misspelling 'Asign' in 'Finish validation' confirmation window

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#226]
_Issue came from UAT_

**Preconditions:**
An extraction job is created, all annotation tasks within it are finished.

**Steps**
1. Open validation task as assigned user
2. Select “Valid” in the bottom of panel with labels
3. Click “Finish validation” button. A dialog window appears
image

**Result:** 
The label 'Asign' is in the window.

**Expected result:**
'Assign' should be there.

**Comment by khyurri** [comment]
Fixed in: #190

**Comment by khyurri** [comment]
Released in 1.4.0
