### ISSUE TITLE
Validation cannot be finished by pressing 'Finish validation' button

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#227]
_Issue came from UAT_

**Preconditions:**
An extraction job is creates, all annotation tasks within it are finished.

**Steps**
1. Open validation task as assigned user
2. Select “Valid” in the bottom of panel with labels
3. Click “Finish validation” button. 
4. Click “Confirm validation and assignment” button.
5. Open some other page, then open the same validation task again. 

**Rusult:**
Status is not “Finished”.

**Comment by khyurri** [comment]
Possible duplicate: #190

**Comment by sbilevich** [comment]
https://github.com/epam/badgerdoc/issues/177

**Comment by DaryaGurtovenko** [comment]
Verified, closed
