### ISSUE TITLE
Infinite indication of loading of taxonomy data when searching for input missing in the taxonomy

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#229]
_Issue came from UAT_

**Preconditions:**
1. A category and an associated taxonomy exist.
2. An extraction job with at that category and taxonomy is created and started.

**Steps:**
1. Open the annotation task.
2. Select the category with taxonomy and create a label over some part of text. 
The right sidebar switches to the “data” tab, and a search bar appears below.
3. Enter something that is not a substring of any entries display names in the taxonomy. 

**Result:**
Animation of loading (jumping three dots) appears and runs indefinitely.

**Expected result:**
'Nothing was found' or similar text should be shown.

**Comment by MarinaVorobeva21** [comment]
Reopen this issue as reproduced on dev1.

**Comment by Iogsotot** [comment]
fixed by https://github.com/epam/badgerdoc/pull/590

**Comment by MarinaVorobeva21** [comment]
fixed
