### ISSUE TITLE
Taxonomy: Cannot add entities with the same name to a new version of a taxonomy

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#230]
_Issue came from UAT_

**Preconditions:**
A taxonomy is created.

**Steps:**
1. Add an entity with some name to the most recent version of the taxonomy using a POST request to the `/taxons `API endpoint.
2. Create a new version of the taxonomy using a POST request to the `/taxonomy `API endpoint.
3. Try to add the same entity with the same name to the newly added version of the taxonomy. 

**Result:**
Response 400 “Field constraint error. Taxon name must be unique." appears.

**Expected result**:
It should be possible to add entities with the same name to a new version of a taxonomy

**Comment by MagicTearsAsunder** [comment]
Hint: [](https://github.com/epam/badgerdoc/blob/main/taxonomy/app/taxon/services.py#L43)

**Comment by andgineer** [comment]
well I am not sure I fully understand the DB model
should not we check that this is unique taxon name for this taxonomy version?
and why now we do not check taxonomy at all and want the taxon name to be unique for this tenant for all taxonomies?

**Comment by andgineer** [comment]
https://github.com/epam/badgerdoc/commit/fecf26b9e355afa420a741ffe6a9680526b75907
