### ISSUE TITLE
Unable to delete a taxonomy version by its ID and version

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#231]
_Issue came from UAT_

**Preconditions:**
A taxonomy with at least two versions is created. 
Version 1 has associated taxons, version 2 has no associated taxons

**Steps:**
1, Authorize with token.
2. Send a DELETE request to the `/taxonomy/{taxonomy_id}/{version}` endpoint with parameters corresponding to version 2 of the 
taxonomy (e.g., using Swagger).

**Result:**
Response 500: Internal Server Error is returned
![image](https://user-images.githubusercontent.com/80756170/213181758-458da4be-8db2-47c1-96a2-8aa31f9f4727.png)

**Comment by DaryaGurtovenko** [comment]
The issue is not reproduced. 
The taxonomy v2 can be deleted, and after the deletion resaved the same taxonomy v1 gets again v2.

**Comment by spiridonovfed** [comment]
The bug is not redproducing now

**Comment by spiridonovfed** [comment]
@zefiris87 could you please check if you can reproduce. If not - we'll close it

**Comment by zefiris87** [comment]
Verified. Everything is ok. I'm closing the issue

**Comment by zefiris87** [comment]
Verified. Everything is ok. I'm closing the issue
