### ISSUE TITLE
Assets: Consequent files uploads result in 504 Gateway Timeout and freeze the assets service for some time

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#237]
**Preconditions:**
There are many small text files to be uploaded. 
Group the text files in batches of size of anywhere between 1 and 100, so that there are several batches of files.

**Steps:**
1. Upload batches synchronously one-by-one via POST requests to the API endpoint `/files` of the assets service.
2. Monitor the responses

**Result:**
Some request will result in response 504 Gateway Timeout. 
The larger a batch is, the more likely it is to cause such response. After that the service freezes and responds with 504 to any other requests, and the Documents page in UI can’t load existing documents. The duration of this effect seems to be proportional to batch size.

**Comment by Nathicanaa** [comment]
@DaryaGurtovenko
We've increased allocated resources for file converting service and it seems like the problem is gone. 
Could you please check for that?

**Comment by DaryaGurtovenko** [comment]
Last test shown that there is no such error, should work
