### ISSUE TITLE
 Some taxons disappear after saving draft or finishing annotation task

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#246]
**Preconditions:**
Annotation job with at least one category with taxonomy attribute is created and started.

**Steps**
1. Log in as annotator for the corresponding annotation task.
3. Annotate the document with several labels.
4. Click the “Save draft” or the “Finish annotation” button, wait for the browser page to refresh.

**Result:** 
Some taxons are no more shown on their corresponding tags.

Successive corrections do not help circumvent this issue. If annotator re-assigns some or all missing taxons, it might cause the same or other taxons to disappear.
This bug can happen with annotations jobs with hierarchical and extensive coverage type, and possibly other types as well.

**Comment by sbilevich** [comment]
fixed in 1.4.0
