### ISSUE TITLE
Document-level labels are not visible during validation

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#247]
_Came from UAT_

**Preconditions:**
At least 3 users exist (2 annotators and 1 validator).

**Steps:**
1. Annotate a document with some document-level labels as both annotators.
2. Log in as validator, start the corresponding validation task. 

**Result:**
Document-level labels assigned by annotators are not visible.

The bug occurs under certain conditions. It appears that one possible condition is that validator is not annotator of the same document at the same time, or another possible condition is that validator is also annotator of the document and there are at least 2 other annotators.

**Comment by sbilevich** [comment]
Needs to be done as feature

**Comment by MarinaVorobeva21** [comment]
Fixed
