### ISSUE TITLE
Validation task cannot be finished with extensive coverage

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#248]
_Came from UAT_

**Steps:**
1. Create an annotation job of type “extensive coverage”.
2. Make annotations of some document within the annotation job by all annotators.
3. Log in as validator, validate the document.
4. Click the “Save draft” or the “Finish validation” button. 

**Result:**  
A success notification appears in the lower left corner, but the status of validation task remains “In progress”.

**Comment by sbilevich** [comment]
Request URL:http://dev1.badgerdoc.com/api/v1/annotation/tasks/2055/finishRequest Method:POST Status Code:500 Internal Server ErrorInternal server error. 'AgreementScoreServiceException' object has no attribute 'exc_info'

**Comment by MagicTearsAsunder** [comment]
fixed [here](https://github.com/epam/badgerdoc/pull/297)

**Comment by MarinaVorobeva21** [comment]
Fixed

**Comment by MarinaVorobeva21** [comment]
Fixed dev1
