### ISSUE TITLE
Converter: Some Unicode characters are replaced with a question mark after upload

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#249]
_Came from UAT_

**Preconditions:**
There are text documents containing Unicode characters ready to be uploaded.
See example below:
![image](https://user-images.githubusercontent.com/80756170/214522723-813533a3-ecc8-4f4e-94b4-58173fbc5653.png)

**Steps to reproduce:**
1. Ensure the text is properly displayed in notepad.
2. Upload the documents and open them in BadgerDoc UI. 

**Result:**
Some Unicode characters are replaced with question marks.

**Comment by thinklab** [comment]
[test_unicode_file.txt](https://github.com/epam/badgerdoc/files/10547203/test_unicode_file.txt)

**Comment by DaryaGurtovenko** [comment]
Verified on attached and extended files.
