### ISSUE TITLE
No distinction between different versions of taxonomy when creating an annotation job

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#253]
_Issue came from UAT_

**Preconditions:**
1. At least one category with attribute of type “taxonomy” exists.
2. At least two versions of the taxonomy exist

**Steps to reproduce:**
1. Start creating a new annotation job.
2. Select some documents for labeling. Go to the next page.
3. Enable the category with associated taxonomy for labeling. A new widget appears for taxonomy selection.
4. Try to select a taxonomy for the category. 
There are as many choices for it as versions with no possibility of distinguishing between versions.
5. Select any of them and reopen the widget.
 
**Result:** 
All choices are marked as selected.

**Comment by MarinaVorobeva21** [comment]
An error is displayed after choosing the taxonomy version.

https://user-images.githubusercontent.com/98399603/217794281-58e6f2bc-9c95-4216-9ea5-39fe78579eea.mp4
