### ISSUE TITLE
Upload wizard doesn’t add uploaded documents to a newly created dataset

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#255]
**Preconditions:**
There are some documents ready to be uploaded

**Steps to reproduce:**
1. On the “Documents” page of BadgerDoc, click the “Upload Wizard” button in the upper right corner.
2. Select a few documents for upload and click the “Next” button.
3. Under “Do you want to add files to dataset now?” select “New dataset” and enter a name for it.
Proceed to the end of upload. The page redirects to “Documents”. 

**Result:**
The dataset is created, but no documents are added to it

**Comment by Iogsotot** [comment]
@DaryaGurtovenko pls check (when env is ready)
