### ISSUE TITLE
Sorting of tasks of an annotation job works only by type

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#258]
_Issue came from UAT_

**Preconditions:**
An annotation job with a several tasks exists.

**Steps to reproduce:**
1. Go to Extractions > {EXTRACTION_NAME} > Tasks. 
2. Try to sort tasks by any column other than type (e.g., “File name”). 

**Result:**
The order of tasks doesn’t change.

**Comment by Iogsotot** [comment]
This is not a bug, it works as expected: where sorting is added, it works, where it is not added, it does not work (Job Name, File Name, Pages)
![image](https://user-images.githubusercontent.com/50149163/215742471-129445aa-1f7a-4991-8c6c-5f165a15d471.png)
