### ISSUE TITLE
Some colors of category highlighting are opaque and obscure selected text

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#259]
_Issue came from UAT_

**Steps to reproduce:**
1. Set the color for the category to for example “teal” or “blue”.
2. Create an annotation job with this category enabled.
3. Annotate some chunk of text with this category. 

**Result:** 
The highlighted text gets obscured
![image](https://user-images.githubusercontent.com/80756170/214528696-ec19f978-f647-4dd9-a206-de0d53e521cc.png)

**Comment by sbilevich** [comment]
Colours should be in Hex Code RGB("#000000), “teal” or “blue” doesn't support opacity.
