### ISSUE TITLE
Label information is shown over every line of a multiline label

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#260]
_Issue came from UAT_

**Preconditions:**
An annotation job with at least one category of type “box” is created and started

**Steps to reproduce:**
1. Open an annotation task.
2. Create a label that spans over multiple lines. 
 
**Result:** 
Label info is shown over every line
![image](https://user-images.githubusercontent.com/80756170/214529000-821c9a4f-8293-4555-8b13-aadfa3877f11.png)

This can be considered an issue, because such behavior causes ambiguity: is this one label over a big portion of text or multiple labels over smaller chunks?

**Comment by sbilevich** [comment]
reproduced only on txt docs

**Comment by khyurri** [comment]
Possible duplicates: https://github.com/epam/badgerdoc/issues/264

**Comment by MarinaVorobeva21** [comment]
Fixed
