### ISSUE TITLE
Multiple copies of the same label can be spawned during validation

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#261]
_Issue came from UAT_

**Preconditions:**
An annotation job assigned to at least 2 users exists (e.g., one annotator and one annotator+validator).

**Steps to reproduce:**
1. Finish annotation tasks for some document.
2. Open the validation task.
3. Click on some label made by an annotator multiple times. 
 
**Result:** 
After every click, an instance of that label is added to the validation area.
![image](https://user-images.githubusercontent.com/80756170/214529439-2fca5251-d053-41cd-9b30-522bd7260158.png)

**Comment by MarinaVorobeva21** [comment]
Fixed
