### ISSUE TITLE
Pages summary returns incorrect response

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#263]
_Issue came from UAT_

**Preconditions:**
1. Authorization token is provided.
2. An annotated and validated document exists.

**Steps to reproduce:**
1. Send request to the `/tasks/{task_id}/pages_summary` endpoint of the annotation service with id of the validated document.
2. Check the response. 

**Result:**
The response only contains entries in the "not_processed" field.
![image](https://user-images.githubusercontent.com/80756170/214530205-15f8a150-c2af-40a4-a872-fcdef260e030.png)

**Comment by thinklab** [comment]
Can't repro. With task_id 2033 endpoint returns correct response:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/26768572/215765950-a304ef8d-037a-49e9-8707-458f722999b1.png">
<img width="650" alt="image" src="https://user-images.githubusercontent.com/26768572/215766099-1e40c79c-31dc-4876-890e-f7db507378c0.png">
