### ISSUE TITLE
The animation with three dots when there is no category in list and they cannot be displayed

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#266]
Old defect returns - we have animation with three dots when there is no category in list and they cannot be displayed.

**Steps to reproduce:**
1. Create job with only one category with taxonomy.
2. Open the job as annotator.

**Result:**
In category list of right tab three dots animation is shown even if nothing to be show,

**Expected result:**
We shouldn't show this animation because it seen as something is working at the moment

**Comment by Iogsotot** [comment]
@DaryaGurtovenko pls check (when env is ready)
