### ISSUE TITLE
The button 'Add label' of annotation jobs doesn't work 

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#267]
We didn't have this issue before, something was broken recently. 

**Preconditions:**
Some job for annotation is created

**Steps to reproduce:**
1. Open the job.
2. Try to create the label via button '+ Add Labels'.

**Result:**
It's impossible to add label,

**Expected result:**
The button '+ Add Labels' should work and it should be possible to create labels with it.

**Comment by Iogsotot** [comment]
@DaryaGurtovenko pls check (when env is ready)
