### ISSUE TITLE
New revision should contain only latest changes

### ISSUE THREAD

**Issue by MagicTearsAsunder** [epam/badgerdoc#279]
Steps to reproduce:

1. For the annotation task, set any label. Finish task.
2. Go to the validation task and mark page as invalid. Finish task. New annotation task would be created.
3. Go to the new annotation task, make an annotation. Save draft.

You can use [this](http://dev2.badgerdoc.com/annotation/tasks/861?jobId=1024) task.

Front-end's request body POST http://dev2.badgerdoc.com/api/v1/annotation/annotation/861:
```
{
    "user": "a6511931-ddbc-4ea5-a885-5653773d5d48",
    "pages": [],
    "base_revision": "f2876a0cb849509d91800ef9a33f83c1dc6fbca3",
    "validated": [],
    "failed_validation_pages": [
        1
    ],
    "categories": [
        "labels_test_category_id"
    ],
    "links_json": []
}
```
Backend's response 400
```
{
    "detail": "This task is for annotation. There should not be any pages in validated and failed arrays. Pages in validated: set() Pages in failed: {1}"
}
```

In Request Body fields "categories" and "failed_validation_pages" are not empty. 
Instead, a new revision (annotation) should be created having only field "pages" not empty.
Remember, revision is the latest changes, not the whole current state.

**Comment by sbilevich** [comment]
Pages will be filled only if annotation of a document(draw annotations) has been done. Editing of categories and links for document also an annotation and creates a revision. Need to be discussed with @MikhailFokanov
