### ISSUE TITLE
Hide add labels button on document view

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#285]
Hide button and disable labels selection
![image](https://user-images.githubusercontent.com/69203629/215765039-8ec4850a-1111-45e1-86d4-bfdde6569977.png)
http://dev2.badgerdoc.com/documents/518?jobId=1031&revisionId=c0f79f1a61570020ec174f0d8795c474f54d7dcb

**Comment by MarinaVorobeva21** [comment]
Fixed
