### ISSUE TITLE
Repeated transferring of span without any value in the validation task

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#290]
_Came from UAT_

Reproduced occasionally 
**Preconditions:**
Transfer of span in the validated version

**Steps to reproduce:**
1. Click was by Imposition span for validated version transferred Category without any value. 

**Result:**
This category span can’t be updated in the validated version, value can’t be added.
![image](https://user-images.githubusercontent.com/80756170/215796168-43d461fc-e16a-4f38-9353-7be44a196ccd.png)
![image](https://user-images.githubusercontent.com/80756170/215796199-197e8c36-a2e5-4661-83da-f639fe6e97e2.png)

**Comment by Iogsotot** [comment]
Possible duplicate https://github.com/epam/badgerdoc/pull/361

**Comment by MarinaVorobeva21** [comment]
Fixed
