### ISSUE TITLE
Transferring relation from an annotation of different users does not work correctly

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#291]
_Came from UAT_

**Steps to reproduce:**
1. Jurisdiction 1 (from annotation 1) is transferred to the validated version,

**Result:**
Relationship 4 (from annotation two) cannot be transffered. 
The same situation when transferring Jurisdiction 2, then relationship 3 cannot be added to the validated version.
![image](https://user-images.githubusercontent.com/80756170/215796743-84db092c-6d1c-4a15-98f8-d2f72a091f04.png)

**Comment by MarinaVorobeva21** [comment]
Fixed
