### ISSUE TITLE
Validated version with 2 annotations instead of 3 should be available to save and to finish with warning

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#292]
_Came from UAT_
During the course of the project, the requirement can be changed for business reasons, and the number of annotations is reduced to 2.

**Preconditions:**
1. Annotation job with 3 annotators is created

**Steps to reproduce:**
1. Try to finish the job with 2 annotators only.

**Expected result:**
Validated version with 2 annotations instead of 3 should be available to save and to finish with warning.

**Comment by khyurri** [comment]
User, who can manage job, can remove annotator from this job and "redestribute" not finished tasks between other annotators.

@DaryaGurtovenko please, verify it's working

**Comment by DaryaGurtovenko** [comment]
Admin is able to re-distribute existing job between another set (via 'Edit') of annotators, so this workaround can be used.

**Comment by sbilevich** [comment]
#304 #331 should be done to fix an issue

**Comment by Iogsotot** [comment]
need changes on backend side: "extensive_coverage" field returns wrong
<img width="214" alt="image" src="https://user-images.githubusercontent.com/50149163/221202695-2225c19e-5620-4f54-a137-df163b8782d5.png">
<img width="220" alt="image" src="https://user-images.githubusercontent.com/50149163/221202841-191714b2-3ba5-4b5e-89cd-5d1ca2425c7c.png">
<img width="203" alt="image" src="https://user-images.githubusercontent.com/50149163/221203064-c0fc2ab6-5adf-48d3-83f7-10e0f7ad3ee8.png">
@andrei-shulaev

**Comment by zefiris87** [comment]
@andrei-shulaev 

If User try to save edited job, the following error appears:

"Failed request to the Annotation Manager: 500, message='Internal Server Error', url=URL('http://annotation/jobs/1962')"

And there is 422 response for the job request (as far as I understand)

![image](https://user-images.githubusercontent.com/124054458/223441166-31f4621b-aadd-4b9e-b45c-78f728e28519.png)

**Comment by khyurri** [comment]
Will be closed during: https://github.com/epam/badgerdoc/issues/425

**Comment by zefiris87** [comment]
Can't complete validated version. The following popup appears, but "Confirm validation" doesn’t work.

Job is http://dev1.badgerdoc.com/annotation/tasks/3971

![image](https://user-images.githubusercontent.com/124054458/228529164-63204ee0-868d-4f00-a688-a5a2c078fda2.png)

**Comment by MarinaVorobeva21** [comment]
_Bug2:_

**Precondition:**
Create an extraction with 2 annotators and 2 validators. One of them is an annotator and validator (e.g. annotator1).  The second one is the annotator only (annotator2)
Create an annotation with annotator2, but do not finish the annotation task.
**STR:** 
- Go to the extraction
- Tap on Edit
- Delete the annotator2 (the same as validator)
- Save the extraction
- Go to the extraction jobs
- Open the validator job
- tap on the annotation made by annotator2

**AR:** 
The tab on the right has an empty name.
![image](https://user-images.githubusercontent.com/98399603/229153450-a1bd82a4-f0b3-478d-91f1-768e0264d371.png)

**ER:**
The tab on the right is named after deleted annotator2, who created the annotation.

**Comment by MarinaVorobeva21** [comment]
Fixed. Editing the Extraction is working.
