### ISSUE TITLE
Saving filter settings when changing user

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#295]
_Came from UAT_

When changing the User, the task filter settings are saved, while the settings of the new user are displayed as basic, however, in order to reset them or display new ones, new checkboxes must be set.

**Steps to reproduce:**
1. Select documents in the 'In Progress' status as Annotator 1.
![image](https://user-images.githubusercontent.com/80756170/215799175-c25fe5a2-ab31-438f-8f96-d4e3d784fb8f.png)
2. Change User, open dashboard as Annotator 3.
![image](https://user-images.githubusercontent.com/80756170/215799357-ea8869f4-cf66-4753-84ba-3e8bac89c95e.png)

**Result:**
Since Annotator 3 has no 'In Progress' documents, no tasks are displayed. 
For Tasks to appear, you need to configure the filter again even if the filter seems to be clear.

**Comment by MarinaVorobeva21** [comment]
Fixed
