### ISSUE TITLE
Annotation service: pytest failed in some tests

### ISSUE THREAD

**Issue by khyurri** [epam/badgerdoc#3]
If you run `pytest` in annotation service, it fails in different tests: minio, botocore and others. Seems that `docker-compose.yml` doesn't contain all required services as dependency.

**Comment by spiridonovfed** [comment]
All tests are fixed. Fix is in 'develop' branch now. CI pipeline is green. Issue can be closed

**Comment by spiridonovfed** [comment]
Fixed in https://github.com/epam/badgerdoc/pull/85
