### ISSUE TITLE
UX checkup and cleanup

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#305]
1. Create environment variable???
2. Hide pipeline-related data from UI

**Comment by Iogsotot** [comment]
Dashboard
![image](https://user-images.githubusercontent.com/50149163/216927723-d21ad147-a925-4585-8a3b-282896b74d9d.png)

Job creation
![image](https://user-images.githubusercontent.com/50149163/216929387-2dde8ce2-d722-4444-8868-9526d01c332b.png)
![image](https://user-images.githubusercontent.com/50149163/216929466-d01f9800-baee-48cf-a751-2599e6b0879d.png)

Upload wizard
![image](https://user-images.githubusercontent.com/50149163/216931368-d24c10ab-4a8c-4ca5-89db-e110072ffef8.png)
![image](https://user-images.githubusercontent.com/50149163/216931552-a6507833-6b3f-4f07-89e2-830bcb096046.png)
![image](https://user-images.githubusercontent.com/50149163/216931635-6d22320f-399d-4155-babf-9dffd77957c1.png)

**Comment by Iogsotot** [comment]
upd: 
remove step Preprocessor (Upload Wizard) at all
![image](https://user-images.githubusercontent.com/50149163/217002963-0a79169a-c5a2-45ff-9988-6e86235846a5.png)
(no need for preprocessor)

Pre-selected Extraction and Annotation in the Job Creation and the Upload Wizard
![image](https://user-images.githubusercontent.com/50149163/217003452-a137e930-6d85-465f-b6d0-dfbfe6bc642f.png)

**Comment by khyurri** [comment]
PIPELINES_DISABLED=True
