### ISSUE TITLE
Imported annotations got misplaced. Weird document margins and intervals between letters

### ISSUE THREAD

**Issue by spiridonovfed** [epam/badgerdoc#307]
See an example here:
http://dev2.badgerdoc.com/documents/547?jobId=1084&revisionId=7fff14288bd2cd806bdd5df719441827622e1747

**Comment by spiridonovfed** [comment]
PR merged - https://github.com/epam/badgerdoc/pull/315

**Comment by spiridonovfed** [comment]
Steps to reproduce/test:
go to convert swagger, endpoint /label_studio/import.
Launch it with this body:
{
 "input_annotation": {
 "bucket": "test",
 "path": "test_converter/label_studio_format.json"
 },
 "output_bucket": "test",
 "validation_type": "cross",
 "deadline": "2024-01-24T11:12:19.549Z",
 "annotators": ["45526cca-291a-405e-8234-6088454e18c4", "3675d181-9d31-4d59-91fc-9b24e3a8e486"],
 "validators": []
}

Look for the newest document on BadgerDoc UI in "Documents" tab.
See, that annotations are correctly placed on words "27" and "Jerusalem", they are not displaced

**Comment by MarinaVorobeva21** [comment]
Fixed
