### ISSUE TITLE
Scroll bar for large category list doesn't work properly - all categories are seen on the list

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#310]
**Preconditions:**
Job with large list of category (>16) is created

**Steps to reproduce:**
1. Open the job and pay attention to category list.
2. Try to use scroll by bar or mouse.

**Result:**
Even if scroll bar presents, categories are displayed all together and don't go under scroll bar.
![image](https://user-images.githubusercontent.com/80756170/217528510-a9bdf51b-4689-4629-992a-eed875ebb07c.png)

**Expected result:**
The lower part of the category list should be seen only after scrolling and all the buttons and radio-buttons should be seen.

**Comment by MarinaVorobeva21** [comment]
Fixed
