### ISSUE TITLE
In 'Files' tab of job the left arrow is not disabled on the last page of file list

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#313]
_Minor_
The right arrow also is enabled even for job with one file only, but I described the case for several pages below. 

**Preconditions:**
Extraction job with more than 15 files is created.

**Steps to reproduce:**
1. Open the job, 'Files' tab.
2. Chose with 'Show on page' drop-down amount of file when not all of them are displayed on one page ('15' for 16 files). 
3. Click on pagination arrow until the last page.

**Result:**
It's possible to click on right arrow after the last page, the error occurs:
![image](https://user-images.githubusercontent.com/80756170/217539190-bae36c1c-544c-476a-80af-ee2d5ff65628.png)
In the same time the left arrow is correctly disabled on the first page of list.

**Expected result:**
The right pagination arrow should be disabled on the last page of list.

**Comment by MarinaVorobeva21** [comment]
Arrows are disabled even if more than 15 documents are in the extraction. 
All the documents can be displayed only with a change of "Show on page" number.

**Comment by khyurri** [comment]
Please, do not close after test

**Comment by MarinaVorobeva21** [comment]
Fixed for the Files tab

**Comment by Aleksei-Egorenko-EPAM** [comment]
@MarinaVorobeva21 check please jobs tab too

**Comment by MarinaVorobeva21** [comment]
Fixed for Jobs tab
