### ISSUE TITLE
Multiple choice for transferring labels common for all annotators

### ISSUE THREAD

**Issue by khyurri** [epam/badgerdoc#314]

**Comment by DaryaGurtovenko** [comment]
The idea of task is add the possibility to automatically transfer all matching annotations from annotators during split validation

To check:
**Preconditions:**
Extraction job for at least 2 annotators is created.

**Steps to reproduce:**
1. As annotator 1 add several labels.
2. As annotator 2 add some **the same** labels.
3. As annotator 2 add some **different** labels.

**Expected result:**
1. Automatic transfer of all matching annotations should be available. 
2. Different annotations should be distinctive and accessible.

**Comment by khyurri** [comment]
Check why `style` attribute may be omitted in some responses

**Comment by khyurri** [comment]
Let's compare fields: `id` `text` `x` `y` `width` `height`

**Comment by MarinaVorobeva21** [comment]
Verified
