### ISSUE TITLE
Remove unnecessary request

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#320]
When drawing annotation, request to link_category should be sent only if selected category has taxonomy data attribute
![image](https://user-images.githubusercontent.com/69203629/217849295-4e561e83-0f19-4113-839f-35d2dae8244b.png)

**Comment by MarinaVorobeva21** [comment]
Still reproduces. Requests for not-taxonomy categories are still sent.
![2023-02-28_16h19_21](https://user-images.githubusercontent.com/98399603/221900584-6f3dd7dd-d98d-40b0-a7b6-e753fe0f69f5.png)
![image](https://user-images.githubusercontent.com/98399603/221900670-75ea316a-c293-4710-85e7-a8209b6f4da9.png)

**Comment by MarinaVorobeva21** [comment]
Fixed
