### ISSUE TITLE
Fix styling on validation view

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#329]
![image](https://user-images.githubusercontent.com/69203629/218452354-5b0e1d40-a93a-4f4c-b493-dfef2846257f.png)

**Comment by MarinaVorobeva21** [comment]
**AR:** Valid and Invalid buttons are NOT attached to the bottom as in the Categories tab ![image](https://user-images.githubusercontent.com/98399603/221893653-8d674f51-a617-438d-bc21-0963c106e5ab.png)
**ER:** Valid and Invalid buttons should be attached to the bottom as in the Categories tab

**Comment by MarinaVorobeva21** [comment]
Validation buttons should be in the same place and have the dividing line above as on the Categories tab (according to @MikhailFokanov comment).
![image](https://user-images.githubusercontent.com/98399603/222496114-391d3638-fb4b-40cc-b8f9-f8aebd41f2ab.png)

**Comment by zefiris87** [comment]
Verified
