### ISSUE TITLE
No taxonomies data on get job by id end-point

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#331]
When getting job, all categories are strings, even if taxonomy is attached to it. 

- [ ] Back-end: Modify end-point so categories are:
"categories": [
    "string",
    {
      "category_id": "123abc",
      "taxonomy_id": "my_taxonomy_id",
      "taxonomy_version": 1
    }
  ]
  
- [ ] In all usages of http://dev1.badgerdoc.com/api/v1/jobs/docs#/default/get_job_by_id_jobs__job_id__get check the type of categories we get to show it correctly on UI.

**Comment by andrei-shulaev** [comment]
Data could be extracted right from taxonomy service. No changes needed.
