### ISSUE TITLE
Add NEXT button for annotator and validator

### ISSUE THREAD

**Issue by khyurri** [epam/badgerdoc#334]
**Front-end**
- [x] Add NEXT with save and NEXT without save functionality. It's ok to add dropdown on `FINISH LABELING` button

** Back-end**
- [x] Add endpoint to annotation service to get NEXT task and PREVIOUS task. This endpoint receives id of current task and must return object: `{next_task: ..., previous_task: ...}` 

**Algorithm how to select next and previous tasks**

Let's simplify and get **ALL** tasks by user_id ordered by same field (id?) and get 2 nearest to current.

**Comment by Andrka** [comment]
@khyurri  Do we need to control the statuses of returned tasks?

**Comment by spiridonovfed** [comment]
back-end side is ready: https://github.com/epam/badgerdoc/pull/371

**Comment by MarinaVorobeva21** [comment]
Verified
