### ISSUE TITLE
Wrong label is changed during validation - when labels belong the same category

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#337]
_Came from UAT_

**Preconditions:**
1. At least one labeling category with associated taxonomy exists.
2. Annotation job (hierarchical validation) is started with at least two different labeling categories (including one with the taxonomy).
3. Some document of the annotation job is annotated with at least three labels of the category with taxonomy, and is ready for validation.

**Steps to reproduce:**
1. Open **Validation** task.
2. Click on one label with associated taxon _(label 01)_, and change it to some other taxon. Change is successful.
3. Click on another label _(label02)_ of the same labeling category with associated taxon from the same taxonomy , and try to change it to some other taxon. The previously selected taxon _(label01)_ is changed.
4. Click on another label _(label03)_ of the same labeling category with associated taxon from the same taxonomy, and try to change it to some other taxon. The first selected taxon (label01) is changed again.

**Result:**
- If click on some label of the same category, and try to change it, then **the first changed** label is changed again.
- If click on some label of some other labeling category, and try to change it, the **correct taxon** is changed.

**Expected result:**
Chosen for change taxon should be changed for both cases:
- the same category;
- other category.

**Comment by MarinaVorobeva21** [comment]
Does not reproduce.

**Comment by sbilevich** [comment]
Click on annotation, not on label!!!

**Comment by MarinaVorobeva21** [comment]
Not reproduced.
