### ISSUE TITLE
The author of the labelling in the validation task

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#342]
_Came from UAT_
The validator should be able to see the name of the annotator in the validation task window (preferably without additional
clicks). 
Necessary for timely feedback to annotators.

**Comment by sbilevich** [comment]
Done for extensive coverage by @Ziprion

**Comment by spiridonovfed** [comment]
from @sbilevich: Ruslan Khyurri  для отображения аннотаторов в таске по валидации нам надо расширить энд-поинтhttp://dev1.badgerdoc.com/api/v1/jobs/docs#/default/get_job_by_id_jobs__job_id__getнужно возвращать annotators как [{ id: string; username: string }], где username - это логин
Нужно это потому что user с ролью annotator не может получить пользователей по их id

**Comment by spiridonovfed** [comment]
from @Anastasia Plyako: it should work while being logged in as an annotator

**Comment by spiridonovfed** [comment]
from @khyurri :
client_id и client_secret должны храниться в users, если нужно достать user_name, то подменять существующий токен на сервисный аккаунт

**Comment by khyurri** [comment]
@Aleksei-Egorenko-EPAM 
Check where this endpoint is also used and prepare for changes (can be received object instead of string)

**Comment by spiridonovfed** [comment]
Changes in front-end and backend are merged to main - https://github.com/epam/badgerdoc/pull/412

**Comment by MarinaVorobeva21** [comment]
Verified 
<img width="1282" alt="Screenshot 2023-03-15 at 20 45 44" src="https://user-images.githubusercontent.com/98399603/225602254-c73d759b-647b-4255-b0bd-d6986cfa66fc.png">
