### ISSUE TITLE
Task should be editable only in Ready or In Progress statuses

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#353]
If task is not in Ready or In Progress statuses:
For annotation task:

- Annotation should be disabled
- Save Draft, Finish Validation should be disabled
- Document tab - labels and links change should be disabled

For validation task: 

- Valid, invalid buttons should be disabled
- Save Draft, Finish Validation should be disabled
- Document tab - labels and links change should be disabled

![image](https://user-images.githubusercontent.com/69203629/220090798-6f3c1503-a3e7-4223-9beb-3b5548d2874d.png)

**Comment by MarinaVorobeva21** [comment]
Valid and Invalid buttons are enabled In Validation tasks with Finished status

https://user-images.githubusercontent.com/98399603/223219019-de7bd2be-4cdf-4e57-affa-5f96f5bd0855.mp4

**Comment by zefiris87** [comment]
Verified
