### ISSUE TITLE
Redirect to extraction page after finish editing

### ISSUE THREAD

**Issue by Iogsotot** [epam/badgerdoc#373]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/50149163/221222093-8273ac9e-096a-4899-a9e6-26bfd1145343.png">

**steps to reproduce:** press the button "Save Edits" 
**Expected result:** return to the previous page
**Actual result:** page does not change

**_Addition_**: button "back" doesn't work correctly too

**Comment by MarinaVorobeva21** [comment]
Fixed
