### ISSUE TITLE
No paragraphs in TXT-PDF converter

### ISSUE THREAD

**Issue by thinklab** [epam/badgerdoc#381]
Input:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/26768572/221621786-e055dc9d-89a7-4604-9d01-29fc4f80f17b.png">
Output without formatting:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/26768572/221621941-fb1f9018-4f15-40f3-8c88-5b01576f4395.png">

**Comment by thinklab** [comment]
done with test file 
[haiku.txt](https://github.com/epam/badgerdoc/files/10842260/haiku.txt)

<img width="566" alt="image" src="https://user-images.githubusercontent.com/26768572/221633473-01eb8afa-d9aa-49da-920b-3a692db8a2a3.png">

**Comment by MarinaVorobeva21** [comment]
Fixed
