### ISSUE TITLE
Fix bug - settings.attributes in processing are changed by mistake

### ISSUE THREAD

**Issue by spiridonovfed** [epam/badgerdoc#42]
Settings.attributes in processing are changed by mistake (see merged PR https://github.com/epam/badgerdoc/pull/30/files) - we need to fix it for correct deployment of processing

**Comment by spiridonovfed** [comment]
PR to fix the issue is ready - https://github.com/epam/badgerdoc/pull/41/files

**Comment by khyurri** [comment]
PR #41 merged
