### ISSUE TITLE
annotation type lost its place

### ISSUE THREAD

**Issue by Iogsotot** [epam/badgerdoc#421]
![image](https://user-images.githubusercontent.com/50149163/224721854-b023b3a6-c621-49a1-b052-48549c33925f.png)
![image](https://user-images.githubusercontent.com/50149163/224725636-9cd0bd5f-e4b9-4df4-8272-d9b64885c723.png)

linked tasks and PR: 
https://github.com/epam/badgerdoc/issues/329#issuecomment-1448348304
https://github.com/epam/badgerdoc/issues/329#issuecomment-1452188693
https://github.com/epam/badgerdoc/pull/318

**Comment by sbilevich** [comment]
same issue with taxonomies tree
![image](https://user-images.githubusercontent.com/69203629/224959051-26f39d23-364a-4b3a-a181-9bf78bcce0d7.png)

**Comment by Iogsotot** [comment]
partially blocked by https://github.com/epam/badgerdoc/issues/426

**Comment by MarinaVorobeva21** [comment]
Fixed
