### ISSUE TITLE
Wrong request from FE to BE users/users/search

### ISSUE THREAD

**Issue by Iogsotot** [epam/badgerdoc#426]
step to reproduce:
1) open an annotation task with categories 

**Expected result:** 
taxonomy tree on the Data tab
or no data info (if no data from BE)

**Actual result:**
no data in Data tab
error 422 in network

![image](https://user-images.githubusercontent.com/50149163/224969867-0b78b65c-a551-4a8d-a423-719b77fb12e3.png)
![image](https://user-images.githubusercontent.com/50149163/224969992-0da93c24-bed0-4069-a49f-207d63343804.png)
![image](https://user-images.githubusercontent.com/50149163/224970078-5dd942b3-2bf0-47d8-ba57-8240712fea38.png)
![image](https://user-images.githubusercontent.com/50149163/224970307-6b571390-fdc6-4045-8c2f-545559f1f4e1.png)

**Comment by Iogsotot** [comment]
![image](https://user-images.githubusercontent.com/50149163/224985035-d3541899-953a-4194-bfe4-fe9815bd04bc.png)

**Comment by khyurri** [comment]
Cannot be reproduced right now
