### ISSUE TITLE
Impossible to annotate the document with  Tax Rate and Jurisdiction categories

### ISSUE THREAD

**Issue by Annaburnazyan** [epam/badgerdoc#429]
**Steps to reproduce**
1)create a new job and add Tax Rate, Jurisdictions categories 
2) Open annotation task and try to annotate with Tax Rate and Jurisdictions

**Actual result**
It's not possible to annotate with Tax Rate, Jurisdictions categories 
"Something went wrong
Sorry for the inconvenience, we’ll get it fixed." appears. 

![MicrosoftTeams-image (40)](https://user-images.githubusercontent.com/126076766/225002585-40e2a186-db8e-4e69-b41f-929f102a4ede.png)
![MicrosoftTeams-image (41)](https://user-images.githubusercontent.com/126076766/225002554-5e863cd2-a85a-436a-bc04-02df73fd2516.png)

**Expected result**
The document is annotated with Tax Rate and Jurisdictions categories

**Comment by Aleksei-Egorenko-EPAM** [comment]
Same reason for crash like #427 and #428

Duplicate
