### ISSUE TITLE
Annotation task cannot be finished for second annotator in extensive coverage 

### ISSUE THREAD

**Issue by Annaburnazyan** [epam/badgerdoc#430]
**Steps to reproduce**
1) create extensive coverage job for 2 annotators 
2) As annotator 1 annotate the document and the job (job finishes successfully)
3) Open the job for annotator 2, annotate the document and finish the job 

**Actual result**
"Saved successfully" message appears, but the annotation job for annotator 2 is not finished. Job status remains "in progress".
 
![MicrosoftTeams-image (42)](https://user-images.githubusercontent.com/126076766/225039500-3bc4a9ef-baf3-48e0-ae74-722630fb72ed.png)
![MicrosoftTeams-image (43)](https://user-images.githubusercontent.com/126076766/225039548-eead6075-32ca-4e0c-a8db-de828fac8fbf.png)

**Expected result**

After clicking "Finish labeling" , the annotation job is finishes and status of task changes to "Finished"

**Comment by khyurri** [comment]
In case of annotation task can not be finished, we have to show error message in front-end

**Comment by Annaburnazyan** [comment]
fixed
