### ISSUE TITLE
[MAJOR] List of categories is limited without pagination 

### ISSUE THREAD

**Issue by zefiris87** [epam/badgerdoc#432]
User can see only the first 100 of categories in the list.

Precondition 

Category with name "category_document_99991242" is already created

Steps

1. Start to create new Extraction and Annotation
2. Open list of categories to choose ones for the job
3. Scroll down
4. category_document_99991242 is not in the list

More categories or pagination are expected

**Comment by MarinaVorobeva21** [comment]
fixed
