### ISSUE TITLE
The system allows to create an extensive coverage job without any validator

### ISSUE THREAD

**Issue by Annaburnazyan** [epam/badgerdoc#436]
**Steps to reproduce**

1) Open extractions
2) Leave "Validators" empty and fill in other fields
3) Select 'Extensive coverage" 
4) Extraction job is successfully created

**Actual result**
The system allows to create extensive coverage job  without validators.
![image](https://user-images.githubusercontent.com/126076766/225609439-9278f3d7-a797-4e5e-b1ca-69e5f034d97f.png)

**Expected result**
The system doesn't allow to create the job, as "Validators" is a mandatory field.

**Comment by zefiris87** [comment]
Verified
