### ISSUE TITLE
Add UII compatible pagination to filterlib 

### ISSUE THREAD

**Issue by khyurri** [epam/badgerdoc#446]
Currently `filter_lib` supports pagination by request:
```
pagination: {
  page_num: ...,
  page_size: ...,
}
```
And response: 
```
pagination: {
    min_pages_left: ...,
    total: ...,
    has_more: ...
}
```
We need to add additional supported format for UII components, which is required `from`, `count` and `has_more`

We could add additional filed to pagination request, like
```
pagination: {
  page_offset: ...,
  page_size: ...
}
```
make all fields optional, but requires `page_num` or `page_offset`

**Comment by spiridonovfed** [comment]
Agreed 'pagination' attribute in response for the new format is:
pagination: {
  offset: ..., 
  limit: ...
  has_more: ...
}

**Comment by khyurri** [comment]
@nanbratan 
Do we really need to change response? Is it possible to use `has_more` flag to continue loading on scroll?

**Comment by spiridonovfed** [comment]
"Search" endpoints checked:
Annotation:
- [ ] [/tasks/search] - Fails with "detail": "Internal server error. Failed request to 'users' microservice: {\"detail\":\"Not Found\"}"
- [x] [/jobs/{job_id}/categories/search]

**Comment by spiridonovfed** [comment]
https://github.com/epam/badgerdoc/pull/451
