### ISSUE TITLE
No title of the annotator on the tab of side bar and on the annotator part of the Validation task (log in NOT as Admin)

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#456]
### **Precondition**:
There is an Extraction with several annotators and several different annotations.
### **STR**:
1. Log in as the second Validator (not Admin)
2. Open the Validation job
3. Tap on the annotation
### **AR**:
No title of the annotator on the tab of side bar and on the annotator part of the Validation task (log in NOT as Admin)

### **ER**:
The name of the other annotator is displayed
![image](https://user-images.githubusercontent.com/98399603/226685575-0f4f2f61-67b3-4135-b909-76216e98ebb1.png)

https://user-images.githubusercontent.com/98399603/226685875-9e6519f6-02c4-4772-adb2-ed15c5692e7d.mp4

**Comment by Iogsotot** [comment]
This is only reproducible if we open the task (log in) **NOT as an Admin** - all other accounts **don't have rights** to get user data and therefore the  UI  cannot render them.
**Need a fix on the backend** or investigate it and find a workaround.

![image](https://user-images.githubusercontent.com/50149163/227044118-16085a49-8724-4ad7-b828-a4ac0a470387.png)
![image](https://user-images.githubusercontent.com/50149163/227044171-b9d98d5e-9ae5-4922-9111-377792634713.png)

**Comment by Iogsotot** [comment]
possible workaround - jobs/jobs/{jobId}

**Comment by Iogsotot** [comment]
https://github.com/epam/badgerdoc/pull/466 add fixes for cross validation type
https://github.com/epam/badgerdoc/pull/462 add fixes for extensive coverage validation type
WIP -  fixes for extensive coverage validation type
