### ISSUE TITLE
Task page design improvments

### ISSUE THREAD

**Issue by nanbratan** [epam/badgerdoc#485]
## Acceptance criteria

1. Task page.
   - Reduce sidebars's hide/show buttons width from 20px to 16px.
1. Document view.
   - Move scale panel(+/- buttons) on the top of the document view and make them smaller.
   - Make paddings between document view and sidebars fixed 16px.
   - Remove label panel(list of labels).
3. Flow sidebar.
   - Change next/prev button appearance.
   - Add go first/go last buttons.
   - Change "selected" behaviour. For not only label is selectable, whole annotation must be selectable(label/path/text).
   - Label's color should be applied as a background color instead of border.

**Comment by MarinaVorobeva21** [comment]
Verified with bug https://github.com/epam/badgerdoc/issues/507 and no labels.
