### ISSUE TITLE
Task page document view grid.

### ISSUE THREAD

**Issue by nanbratan** [epam/badgerdoc#486]
Need to have a select with options 'vertical'/'horizontal' to change orientation of views's grid.

**Comment by MarinaVorobeva21** [comment]
**AR:**
Values in the selector can be deleted.
Next button is not fully displayed.
![image](https://user-images.githubusercontent.com/98399603/233074748-f5e94446-9dd4-4f84-b7b1-fdc684bc5e47.png)

**ER:**
Values are not editable.
Next button is fully displayed.
