### ISSUE TITLE
Add reason why validation can't be confirmed

### ISSUE THREAD

**Issue by zefiris87** [epam/badgerdoc#488]
1. Create hierarchical validation with 2 or more annotators
2. Finish annotations
3. Start validation, validate just one page
4. Try to finish validation (following popup appears)

exp.: error message appears, user get instructions to validate all pages

act.: nothing is happening when user clicks on the "confirm" button

![image](https://user-images.githubusercontent.com/124054458/228539471-1ad501d2-51b1-42af-b179-92ad5dca4b71.png)

**Comment by Iogsotot** [comment]
Fixed the logic for validation: now the button finish validation is only available if all pages have been marked as valid or invalid, so the wronng modal won't appear

**Comment by MarinaVorobeva21** [comment]
Fixed
