### ISSUE TITLE
It is not possible to scroll  the categories list 

### ISSUE THREAD

**Issue by Annaburnazyan** [epam/badgerdoc#492]
**Steps to reproduce**
1)create a new extraction job and add many categories
2) Open as annotator and try to scroll down the categories list

**Expected result**
It is possible to scroll up and down and see all categories.

**Actual result**
There is no possibility to scroll and see other categories.

Environment 
![MicrosoftTeams-image (45)](https://user-images.githubusercontent.com/126076766/228862011-8eb68477-4120-4d02-b370-b2923fcd5c60.png)

Vertex

**Comment by Iogsotot** [comment]
fixed

**Comment by MarinaVorobeva21** [comment]
Fixed
