### ISSUE TITLE
Re-uploading the same file takes a lot of time

### ISSUE THREAD

**Issue by zefiris87** [epam/badgerdoc#496]
1. Upload a file
2. Upload the same file again

exp.: File uploading takes the same time as for the first upload
act.: Uploading takes some unpredictable time. Sometimes file is being upload only if user try to upload something else.

**Comment by spiridonovfed** [comment]
For now, the system does not upload the same file twice - the same file with the same filename is not uploading for the second time. Not sure if that's expected behavior or not, but the original bug is not reproducing anyway.
@zefiris87 please re-check me

**Comment by spiridonovfed** [comment]
After more deep investigation we found out, that it is not possible to upload the same file without refreshing the page.
Obviously, it has something to do with context on frontend side.

If we upload some file -> refresh the page -> upload the same file - it takes the same amount of time on dev1.
@zefiris87 please re-check it
