### ISSUE TITLE
Links handling at Flow sidebar

### ISSUE THREAD

**Issue by nanbratan** [epam/badgerdoc#497]
Each annotation must have an icon(3 dots).
On click on this icon user should see a dropdown with list of links.
Each link have to contains icon of link's direction(from annotation/to annotation).
Each link have to contains remove icon(cross) to remove the link.
On click on a row with link user - annotation by this link should be selected.

**Comment by MarinaVorobeva21** [comment]
Different links not always can be done from one to another annotation (see the video).

https://user-images.githubusercontent.com/98399603/234327902-722553f5-363e-4fc2-a9a5-7f9eb1937c85.mp4

**Comment by MarinaVorobeva21** [comment]
Fixed
