### ISSUE TITLE
Unable to finish validation (extensive coverage)

### ISSUE THREAD

**Issue by Andrka** [epam/badgerdoc#504]
![04042023-15 00](https://user-images.githubusercontent.com/14347940/229773819-e20b65e3-614b-4cfe-9ae6-6556fee6db1a.png)

### Preconditions:
Job with extensive coverage are created and started.
All annotation tasks are finished.

### Steps to reproduce:
Go to the validation task.
Take annotations from only one annotator.
Try to finish validation.

### Result:
Unable to finish validation.

### Expected result:
Validation is finished.

**Comment by MarinaVorobeva21** [comment]
Fixed
