### ISSUE TITLE
Unlock buttons "Deploy" and "Edit" on the models screen 

### ISSUE THREAD

**Issue by serereg** [epam/badgerdoc#516]
Unlock buttons "Deploy" and "Edit" on the models screen 
![image](https://user-images.githubusercontent.com/56562368/230894034-0686f38e-a875-4799-a975-4a150c54ab1a.png)

**Comment by Iogsotot** [comment]
The buttons are not disabled, they have no logic - if you click on them, no function will be called.

It is necessary to describe the scenario and the logic that needs to be implemented by clicking on each of the buttons

**Comment by serereg** [comment]
For deploy use /api/v1/models/docs#/models/deploy_model_models_deploy_post
For edit use /api/v1/models/docs#/models/update_model_models_update_put
For delete (it is also needed) use /api/v1/models/docs#/models/delete_model_by_id_models_delete_delete

Necessary fields are listed under the buttons
![image](https://user-images.githubusercontent.com/56562368/233013730-d06524a0-29ba-4043-9cb4-122e7a3727fd.png)

**Comment by MarinaVorobeva21** [comment]
Verified
