### ISSUE TITLE
Annotators must be not able to see other's annotations

### ISSUE THREAD

**Issue by nanbratan** [epam/badgerdoc#529]
Steps to reproduce:

1. Create job with extensive coverage type.
2. Add 2 annotators and 1 validator.
3. Annotate document with first annotator(complete annotation task for first annotator).
4. Start annotation activity(open second annotator's annotation task) with second annotator.

Second annotator can see first annotator's tab in left sidebar. Annotator is available to get other annotators's annotations via API.

Expected behaviour:
1. Annotator doesn't see other annotators's annotations

Actual behaviour:
1. Annotator can see other annotator's annotations

**Comment by MarinaVorobeva21** [comment]
Fixed
