### ISSUE TITLE
Annotation: ability to assign multiple (separate) tasks for multiple annotators to annotate the same page (for extensive coverage)

### ISSUE THREAD

**Issue by khyurri** [epam/badgerdoc#53]
Task is for annotation of particular pages of the document. 
One annotator (and one validator) is assigned to the particular pages of the document. 

This logic must be improved: 
The tasks should be created and distributed among multiple annotators, so that extensive_coverage (the integer field in the annotation_job) annotators will annotate the page.

------- 
Annotator: user 
Job: extraction job. Contains annotators, documents, categories + taxonomies, annotation type.
Annotation type: cross validation, hierarchic validation
Cross validation: Automatically assigns some annotators as validators
Hierarchic validation: Assign some users as annotators, some as validators

We need to add new annotation type: extensive coverage
Extensive coverage: One task can be assigned to many annotators

## General algorithm

When user creates new job, user can select how much users will be assigned to one task (extensive coverage) **N**

Task: exact pages in exact document assigned to 1 annotator. This logic must be saved. 
We need to create tasks to **N** annotators. 

We have algorithm to assign task between annotators. Count of pages must be multiplied on N. For example, if we have to distribute originally 100 tasks between 4 annotators, and extensive coverage equals 3, so we need to create `3 * 100 = 300` tasks and assign it between 4 annotators EXCLUDING duplications. So that mean, 1 must annotate 1 page exactly once.

Compatibility with current implementation: This is new validation type, all previous validation type must be the same as now

When BD shows progress, it must be recalculated with extensive coverage multiplication

## Front-end

Add in drop down menu new validation type: Extensive coverage
Open form with 1 additional input: count of annotators. All others inputs must be the same as hierarchical validation.

**Comment by MikhailFokanov** [comment]
@andrejshulaev please reach out to me for details.

**Comment by khyurri** [comment]
Released in 1.2.0
