### ISSUE TITLE
Dialog window doesn’t close automatically after validation is finished

### ISSUE THREAD

**Issue by nanbratan** [epam/badgerdoc#533]
Step to reproduce:

1. Create job with cross validation.
2. Complete annotator's task.
3. Enter validator's task, mark pages as invalid, press finish.
4. Click "Confirm validation and assignment" button at opened modal window.

Expected behaviour:
Modal window is closed and user redirected to another page.

Actual behaviour:
Modal window isn't closed and user stays on the same page.

**Comment by Iogsotot** [comment]
duplicate https://github.com/epam/badgerdoc/issues/494

**Comment by MarinaVorobeva21** [comment]
Fixed
