### ISSUE TITLE
[CRITICAL] Categories panel is not scrollable

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#536]
Steps
Open a labeling task having a large amount of labeling categories (the meaning of “large” in this context depends on the resolution of one’s
monitor).
The categories panel (the one on the right) takes all vertical space and is not scrollable, making it impossible to change annotation type.
![image](https://user-images.githubusercontent.com/98399603/232768369-b406f521-a345-4649-b590-5ddbbff70f87.png)

**Comment by nanbratan** [comment]
Was fixed in this task: https://github.com/epam/badgerdoc/issues/558
