### ISSUE TITLE
[CRITICAL] The labeling of other annotators is visible to the annotator

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#539]
The adjudication labeling method implies the unenviable labeling of the same document by different people. They should not see each other labeling.

![image](https://user-images.githubusercontent.com/98399603/232769075-36a9c8e0-2e08-4268-9b32-07669501dfd0.png)

**Comment by nanbratan** [comment]
Was fixed in this task: https://github.com/epam/badgerdoc/issues/529

**Comment by MarinaVorobeva21** [comment]
Fixed
