### ISSUE TITLE
[CRITICAL] Link issues: Link creation to the wrong element

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#543]
- creation of several types of labels with the same text selection
- when creating a link, the click was made to the red label
- link was created with one of the orange instead
![image](https://user-images.githubusercontent.com/98399603/232769998-e7ff4c39-8dde-41b2-9a9c-4e9082635f62.png)

Link issues: [occasionally]
Deleting one link, deleted both from one entity to two different ones.
More than one link from and to one entity can’t be transferred in a validation task.
Sometimes the link may be created not from the first time, sometimes it simply is not created.
![image](https://user-images.githubusercontent.com/98399603/232770119-42ad7ca8-ef4f-4ddd-b73e-52b55e198fa2.png)

**Comment by khyurri** [comment]
Currently it's possible to select label for link using left pane. This should solve issue

**Comment by MarinaVorobeva21** [comment]
Fixed
