### ISSUE TITLE
[CRITICAL] Documents couldn't be completed for an unknown reason

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#544]
Different documents, with and without labeling, couldn't be completed by different users.
At first, there was a notification that the changes were saved, then that it couldn't be completed and the document remained in the In progress
status.
Removing all the labels didn't help finish the document neither.
![image](https://user-images.githubusercontent.com/98399603/232770396-4485affd-9546-4fc1-9489-c6c85ece9345.png)
![image](https://user-images.githubusercontent.com/98399603/232770426-4b1572d1-4d43-4c17-b538-76b609fac152.png)

**Comment by spiridonovfed** [comment]
Bug issuer says that the bug was found on two random documents (there were no specific properties of those documents)

**Comment by spiridonovfed** [comment]
Bug is not reproduced
