### ISSUE TITLE
[MAJOR] Hover interferes with labeling

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#546]
Steps
creation of label in the raw.
![image](https://user-images.githubusercontent.com/98399603/232770676-1b96da0c-d842-481f-a737-cba22e6bb3f5.png)

when trying to create a label on a line above the already created one, the hover doesn't allow to label correctly
![image](https://user-images.githubusercontent.com/98399603/232770699-088f704f-ded0-4d3c-b09a-f55a1f729be7.png)

**Comment by nanbratan** [comment]
Was fixed in this task: https://github.com/epam/badgerdoc/pull/561

**Comment by MarinaVorobeva21** [comment]
Fixed
