### ISSUE TITLE
[MAJOR] Infinite upload for the items from hidden dropdown

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#548]
Search settings don't allow searching for items from non-expanded dropdowns.
There is an infinite upload.
![image](https://user-images.githubusercontent.com/98399603/232770837-82b4d920-e615-4175-a06b-1dc9c06e7038.png)
![image](https://user-images.githubusercontent.com/98399603/232770855-a4db55a3-c43b-4451-9d00-7f8c5b5ac9aa.png)

**Comment by serereg** [comment]
It seems that the problem just in a frontend request
![image](https://user-images.githubusercontent.com/56562368/235074434-d55c5cfe-e7a7-4f1c-af23-064d71a5a240.png)
after excluding the filter {field: "parend_id", operator: "is_null"}, it should work properly.

**Comment by MarinaVorobeva21** [comment]
Fixed
