### ISSUE TITLE
[MINOR] Bad rendering within re-opening a document

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#549]
![image](https://user-images.githubusercontent.com/98399603/232773116-a3031742-58d6-4270-b5ba-f7748729463d.png)
![image](https://user-images.githubusercontent.com/98399603/232773130-a93d76d0-9f4c-429f-8c4c-2608708b5dd3.png)

**Comment by khyurri** [comment]
@MarinaVorobeva21 
Could you please reproduce this bug and show to @serereg and @nanbratan, they'll check if it's front-end or back-end bug

**Comment by MarinaVorobeva21** [comment]
Me and @Annaburnazyan Cannot reproduce.
