### ISSUE TITLE
[CRITICAL] Manual re-assignment of documents

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#552]
With automatic distribution of documents, all documents are distributed to specific users. If the User can't finish his documents on time: the
validator or the project administrator should be able to re-assign this document to someone else so as not to delay the completion of the entire
Job. It needs re-assignment one-by-one document and by the entire list of unfinished tasks.

**Comment by khyurri** [comment]
This functionality implemented as `Edit Job` and was release in #1.5.1
