### ISSUE TITLE
[CRITICAL] Information provided in the report

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#553]
- The document name is pulled into the column with the annotator ID, the document name column is missing.

![image](https://user-images.githubusercontent.com/98399603/232773855-3fbf8ec1-5306-47e3-9a08-9977ad8bf7c7.png)

- It’s necessary to have the ability to download a report (or tab inside the validator or project administrator dashboard) which document is assigned to which user, with all the filtering and sorting functions.

**Comment by khyurri** [comment]
Cannot be reproduced

**Comment by spiridonovfed** [comment]
PR https://github.com/epam/badgerdoc/pull/593 - 'file_name' field is added to report

**Comment by spiridonovfed** [comment]
After further conversation with bug issuer task 2 changed to this:
- add 'annotator_name' field - annoattor_id is not that convenient
- add scrolling functionality to the page - see issue https://github.com/epam/badgerdoc/issues/592

**Comment by spiridonovfed** [comment]
pt 2 is merged with https://github.com/epam/badgerdoc/pull/600

**Comment by MarinaVorobeva21** [comment]
Fixed
