### ISSUE TITLE
[MAJOR] No filtering by Job Name

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#555]
It's necessary for the absence of blocks to create several Jobs

**Comment by MarinaVorobeva21** [comment]
1. There is no grouping of the names in the list of filter
![image](https://github.com/epam/badgerdoc/assets/98399603/78c35d88-72aa-4067-8923-60a950d3be71)
2. Filtering is not working on other pages from the first one. (Go to the 2nd page and try to filter)
https://github.com/epam/badgerdoc/assets/98399603/190cb253-54ab-48d1-97ca-4ce32c957b77
3. Filtering is not working for all the records (e.g. try to choose job names from the list)
https://github.com/epam/badgerdoc/assets/98399603/6867e728-479b-45a1-b453-43f0c9bf0b1d
4. Sometimes not all the names(records) are displayed in the list. Refreshing the page is needed to see all the records.
5. Mouse wheel scrolling and cursor movement scrolling conflicts

**Comment by MarinaVorobeva21** [comment]
Filtering is not working on the different from the 1st page.
image

The records are not displayed for all chosen filters (e.g. choose 66_1 in Job name filter or 001.jpg in the file name filter)

**Comment by sokolmask** [comment]
Smartfilter is not in scope, consider as ready
