### ISSUE TITLE
[MAJOR] No filtering by File name

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#557]
No filtering by document name in the dashboard if they need to return to a specific document.

**Comment by MarinaVorobeva21** [comment]
The same as for the https://github.com/epam/badgerdoc/issues/555

1. There is no grouping of the names in the list of filter
![image](https://github.com/epam/badgerdoc/assets/98399603/78c35d88-72aa-4067-8923-60a950d3be71)
2. Filtering is not working on other pages from the first one. (Go to the 2nd page and try to filter)
https://github.com/epam/badgerdoc/assets/98399603/190cb253-54ab-48d1-97ca-4ce32c957b77
3. Filtering is not working for all the records (e.g. try to choose job names from the list)
https://github.com/epam/badgerdoc/assets/98399603/6867e728-479b-45a1-b453-43f0c9bf0b1d
4. Sometimes not all the names(records) are displayed in the list. Refreshing the page is needed to see all the records.
5. Mouse wheel scrolling and cursor movement scrolling conflicts
6. When opening the filter for the first time, the loading of the records is too slow.
![image](https://github.com/epam/badgerdoc/assets/98399603/4e1dfef4-6221-484b-8e5c-621e80748976)

**Comment by MarinaVorobeva21** [comment]
- Filtering is not working on the different from the 1st page.
![image](https://github.com/epam/badgerdoc/assets/98399603/8f49d7b6-60d5-4047-972f-b0ebed2b39cf)

- The records are not displayed for all chosen filters (e.g. choose 66_1 in Job name filter or 001.jpg in the file name filter)

**Comment by sokolmask** [comment]
Smartfilter is not in scope, consider as ready

**Comment by MarinaVorobeva21** [comment]
Closed as per the comment above. Smart filter issue https://github.com/epam/badgerdoc/issues/648
