### ISSUE TITLE
update BE api/v1/annotation/annotation/{task_id} for extensive coverage

### ISSUE THREAD

**Issue by Iogsotot** [epam/badgerdoc#569]
When creating a job type: extensive coverage, task: validation, when finishing validation, it is necessary to take into account the possibility of transferring data to the backend for validation and new annotations at the same time (now BE return 422 error).

Actual logic:
if FE send request with this payload
![image](https://user-images.githubusercontent.com/50149163/233994906-baa41c6b-bf99-4896-927d-1978d8a78308.png)
BE response
![image](https://user-images.githubusercontent.com/50149163/233994927-6e62735c-4d0a-4f1c-971f-141725c14f1b.png)

It now works with a workaround with 2 different requests (with data for pages field and with data for validation field separately) and creates 2 revisions instead of 1 revision.

- [ ] update BE  `api/v1/annotation/annotation/{task_id}`
- [ ] update FE to use the new logic

**Comment by MarinaVorobeva21** [comment]
Validated
