### ISSUE TITLE
Possible double common annotations

### ISSUE THREAD

**Issue by Andrka** [epam/badgerdoc#595]
### Preconditions:
Extensive coverage job with 2 annotators and 1 validator is created

### Steps to reproduce:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/14347940/236024482-102c2a8e-a36d-4d38-98c1-870171e3999a.png)

### Result:
Possible double common annotations in validation task

![2023-05-03_23-16](https://user-images.githubusercontent.com/14347940/236024703-0ba9fc4d-467f-498a-9d26-42e5de67c4fc.png)

**Comment by MarinaVorobeva21** [comment]
Fixed
