### ISSUE TITLE
[CRITICAL] Bad rendering of annotations and links on validation task in Extraction coverage

### ISSUE THREAD

**Issue by MarinaVorobeva21** [epam/badgerdoc#610]
**Precondition**:

1. There is an extraction coverage with 3 annotators and a validator.
2. All 3 annotators have finished annotation with links.

**STR**:
Open Validation task

**AR**:
The annotations and links are NOT on the places where they were made.

https://user-images.githubusercontent.com/98399603/236503613-e868041f-8983-4967-bfb2-2085c5b92ae1.mp4

**ER**: 
The annotations and links are on the places where they were made.

**Comment by MarinaVorobeva21** [comment]
Links are not displayed for Validation tasks in a document longer than 1 page

https://github.com/epam/badgerdoc/assets/98399603/478d22a3-7701-4446-bfc9-1fb70426981a

**Comment by Annaburnazyan** [comment]
Verified.
