### ISSUE TITLE
[MAJOR] Unable to delete inside annotation

### ISSUE THREAD

**Issue by Iogsotot** [epam/badgerdoc#613]
Cursor is default (not pointer) and delete on click is not available for inside annotation 
![image](https://user-images.githubusercontent.com/50149163/237048976-05e15ee5-8df1-4c71-982a-909071717d73.png)

**Comment by khyurri** [comment]
Must be possible to delete lablels from left sidebar

**Comment by MarinaVorobeva21** [comment]
Fixed. Annotation can be deleted from the left sidebar.
