### ISSUE TITLE
Filters applied to Dashboard and Extractions pages search are not visible

### ISSUE THREAD

**Issue by dzmitry-butsyanau-epam** [epam/badgerdoc#654]
It would be useful to see list of filters that are currently applied to search component (Dashboard, Extractions pages) that's why sometimes it is not clear why the table is empty and user needs to open each filter to click "select all"

Possible solutions:
1. have a "applied filters" component and show all filters currently applied to search
2. have visual indicator on column title that filter by some value is applied

**Comment by Tokhirov-Abzal** [comment]
Now we have visual indicator which means the filter was applied in this column

![image](https://github.com/epam/badgerdoc/assets/67236305/9392d7a0-7f6c-46db-ba4b-66fb1da53118)

**Comment by MarinaVorobeva21** [comment]
Verified
The indicator is displayed.
