### ISSUE TITLE
Add converter from bbox to offsets in export and import 

### ISSUE THREAD

**Issue by khyurri** [epam/badgerdoc#66]
Add addition converter to export/import between PDF and plain text format. 

BadgerDoc is currently working with PDF and bbox, we need also support plain text with offsets as source format (converter) and export PDF + bbox to plain text with offsets

Part 2: 
- [x] From Label Studio format converter must create bdocs manifest and fill database (AnnotationDocs?)

**Comment by borisevich-a-v** [comment]
https://kb.epam.com/display/EPMUII/Annotation+Microservice – current annotation format is not sufficient for TMT team, as secondary source articles are always in plain text format (so bounding boxes are not sufficient here).
As stated in initial calls, we need to get the offsets of the annotated entities. The following info is required for each tag, assigned to the annotated entity: start_offset, end_offset, entity type, entity name (according to the taxonomy, defined for each entity type).
Example: start_offset = 146, end_offset = 158, entity type = IMPOSITION, entity name = “VAT, 19”.

Relations (e.g. “links”, according to BadgerDoc terminology) should be defined by the governor and dependent entity tags (so each entity tag should be associated with some id).

The format of exported annotations should be sufficient for retrieving the above info. Moreover, the pre-labeled annotations should follow the same format to be imported into BadgerDoc.



Example of a sufficient format (used in our current labeling tool): UIMA CAS XMI https://inception-project.github.io/releases/26.1/docs/user-guide.html#sect_formats_uimaxmi (please see the annotation example attached). A different format may be used but it still should fulfill the above conditions.

**Comment by spiridonovfed** [comment]
How to reproduce import functionality on dev2:
taxonomy/label_studio/import:

POST body:
{
 "input_annotation": {
 "bucket": "test",
 "path": "test_converter/label_studio_format_with_taxonomy.json"
 },
 "output_bucket": "test",
 "validation_type": "cross",
 "deadline": "2024-01-24T11:12:19.549Z",
 "annotators": ["45526cca-291a-405e-8234-6088454e18c4", "3675d181-9d31-4d59-91fc-9b24e3a8e486"],
 "validators": []
}

After endpoint did its logic you can see new document on UI ("documents" tab) with categories, links, document_labels

**Comment by spiridonovfed** [comment]
How to reproduce export to label studio format functionality:
1. Import a file (see the request in the message above) and open this file on UI in 'documents' tab
2. Make a request to taxonomy/label_studio/export with this POST body:
{
  "input_tokens": {
    "bucket": "test",
    "path": "files/file_id/ocr/1.json"},
  "input_annotation": {
    "bucket": "test",
    "path": "annotation/job_id/file_id/annotation_uuid.json"},
  "input_manifest": {
    "bucket": "test",
    "path": "annotation/job_id/file_id/manifest.json"},
  "output_annotation": {
    "bucket": "test",
    "path": "test_converter/some_name.json"}
}
Change job_id, file_id, annotation_uuid to corresponding values of newly created document from step 1 - job_id and file_id are seen in the document URL, annotataion_uuid should be found on minio.
Path in output annotation is up to you.
3. Make the same request as in step 1, but "path" should be the same as output annotation path in step. Newly created document should be the same as resulting document in step 1

**Comment by spiridonovfed** [comment]
Full functionality:
1. Import
    1.1 Annotations - @spiridonovfed - labelstudio_format_test.json
    1.2 Document labels - @spiridonovfed - label_studio_format_with_document_labels.json
    1.3 Taxonomies - @spiridonovfed - label_studio_format_with_taxonomy.json
    1.4 Documents links - @serereg 
2. Export
    2.1 Annotations - @serereg 
    2.2 Document labels - @spiridonovfed 
    2.3 Taxonomies - @spiridonovfed 
    2.4 Documents links - @serereg

**Comment by MarinaVorobeva21** [comment]
Internal Server Error when trying to export a document to MinIO.
![image](https://user-images.githubusercontent.com/98399603/225301480-032b9542-7f40-42fd-b076-063d1e63ce5e.png)
{
  "input_tokens": {
    "bucket": "test",
    "path": "test/files/1016/ocr/1.json"
  },
  "input_annotation": {
    "bucket": "test",
    "path": "test/annotation/2029/1016/33adebf5e1b14605f6cfd6004bf0b45b3fc8118e.json"
  },
  "input_manifest": {
    "bucket": "test",
    "path": "test/annotation/2029/1016/manifest.json"
  },
  "output_annotation": {
    "bucket": "test",
    "path": "doc_link_vma.json"
  }
}

**Comment by spiridonovfed** [comment]
The error above is fixed

**Comment by MarinaVorobeva21** [comment]
Import is working fine.

@serereg Export to MinIO is not working.
Please check on a new document.
{
"input_tokens": {
"bucket": "test",
"path": "files/1045/ocr/1.json"
},
"input_annotation": {
"bucket": "test",
"path": "annotation/2127/1045/88017f57787ef1690ff3e96beb744c265d28d35c.json"
},
"input_manifest": {
"bucket": "test",
"path": "annotation/2127/1045/manifest.json"
},
"output_annotation": {
"bucket": "test",
"path": "test_converter/vma/doc_link_vma.json"
}
}

**Comment by MarinaVorobeva21** [comment]
An error  Error: Unprocessable Entity "detail": "Failed request to 'taxonomy' to get corresponding taxonomy" is displayed while exporting extensive coverage, hierarchical extractions with links and labels.
![image](https://github.com/epam/badgerdoc/assets/98399603/dc64cfce-db0d-4dae-991c-3f4c62707f10)

**Comment by spiridonovfed** [comment]
See related issue: https://github.com/epam/badgerdoc/issues/646
Convert functionality implies there there are several requests to other microservices.
Some of them fail when using tenants = ['not_test', ]

**Comment by MarinaVorobeva21** [comment]
1. Box annotation is imported as text annotation (longer than expected)
![image](https://github.com/epam/badgerdoc/assets/98399603/cd1a5544-9868-4244-9c1c-0a65ccc10fe1)
2. All to all link is imported as Chain

**Comment by spiridonovfed** [comment]
> 2\. If an annotation is not the full word (several symbols), an additional letter is added after each import.

It was fixed recently

**Comment by spiridonovfed** [comment]
> An error Error: Unprocessable Entity "detail": "Failed request to 'taxonomy' to get corresponding taxonomy" is displayed while exporting extensive coverage, hierarchical extractions with links and labels. ![image](https://user-images.githubusercontent.com/98399603/239373186-dc64cfce-db0d-4dae-991c-3f4c62707f10.png)

It is also fixed

**Comment by spiridonovfed** [comment]
> 1. Box annotation is imported as text annotation (longer than expected)
>    ![image](https://user-images.githubusercontent.com/98399603/241211233-cd1a5544-9868-4244-9c1c-0a65ccc10fe1.png)
> 2. All to all link is imported as Chain

this result is expected, should not be considered as bug

**Comment by MarinaVorobeva21** [comment]
Verified
