### ISSUE TITLE
Wrong date shown in tasks table in Extraction

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#68]
![image](https://user-images.githubusercontent.com/69203629/205950754-7df068be-c72f-4ae3-87f6-762ad7bad7a4.png)

**Comment by spiridonovfed** [comment]
Cannot see it on dev1 and dev2.
Correct deadline dates there

**Comment by spiridonovfed** [comment]
Example here: http://dev2.badgerdoc.com/extractions/738

**Comment by spiridonovfed** [comment]
![image](https://user-images.githubusercontent.com/76848937/207539066-5f64f64c-5eea-4498-9a83-170088c60101.png)
Screenshot shows, that we receive "deadline: null" from back-end, not 01/01/1970.

Bug is occurring from front-end side

**Comment by Iogsotot** [comment]
step to reproduce:
http://dev1.badgerdoc.com/extractions/1499 
tab task

**Comment by Iogsotot** [comment]
done https://github.com/epam/badgerdoc/pull/119

**Comment by khyurri** [comment]
Released in 1.2.3
