### ISSUE TITLE
Add Conventional Commits check to GitHub Actions

### ISSUE THREAD

**Issue by cakeinsauce** [epam/badgerdoc#7]
As a developer I want to check that contributors follows convention of commits naming in the repository. We should add [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#specification) check to the CI. Here is a good linter for this purpose written in python which supports pre-commit integration as well: [commitizen](https://github.com/commitizen-tools/commitizen)

DOD:
- [ ] Added commit messages check step in CI

**Comment by thinklab** [comment]
It seems to be easier to install this free app
https://github.com/marketplace/semantic-pull-requests

**Comment by MysterionRise** [comment]
@thinklab it's not maintained anymore, I would be against using it. Let's take a look at some of the alternatives like this Action - https://github.com/amannn/action-semantic-pull-request ?

**Comment by khyurri** [comment]
@MysterionRise 
Amazing, would you prepare PR?
