### ISSUE TITLE
Error during 'annotation' bootstrap locally

### ISSUE THREAD

**Issue by spiridonovfed** [epam/badgerdoc#77]
During local bootstrap of annotation (with docker-compose) we have this:

annotation             | 09-Dec-22 10:33:03 - [INFO] - uvicorn.error - (server.py).serve(84) - Started server process [9]
annotation             | INFO:     Waiting for application startup.
annotation             | 09-Dec-22 10:33:03 - [INFO] - uvicorn.error - (on.py).startup(45) - Waiting for application startup.
annotation             | 09-Dec-22 10:33:13 - [WARNING] - kafka.conn - (conn.py).dns_lookup(1527) - DNS lookup failed for kafka:9092, exception was [Errno -3] Temporary failure in name
 resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
annotation             | 09-Dec-22 10:33:13 - [ERROR] - kafka.conn - (conn.py)._dns_lookup(315) - DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
annotation             | 09-Dec-22 10:33:13 - [INFO] - kafka.conn - (conn.py).check_version(1205) - Probing node bootstrap-0 broker version
annotation             | 09-Dec-22 10:33:23 - [WARNING] - kafka.conn - (conn.py).dns_lookup(1527) - DNS lookup failed for kafka:9092, exception was [Errno -3] Temporary failure in name
 resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
annotation             | 09-Dec-22 10:33:23 - [ERROR] - kafka.conn - (conn.py)._dns_lookup(315) - DNS lookup failed for kafka:9092 (AddressFamily.AF_UNSPEC)
annotation             | 09-Dec-22 10:33:23 - [WARNING] - app.logger - (main.py)._init_search_annotation_producer(957) - Error occurred during kafka producer creating: NoBrokersAvailab
le
annotation             | INFO:     Application startup complete.

The app tries to find kafka, but doesn't find it

**Comment by khyurri** [comment]
Duplicate: #460
