### ISSUE TITLE
Create database for unittest using alembic migrations, not sqlachemy Base.metadata.create_all()

### ISSUE THREAD

**Issue by andrei-shulaev** [epam/badgerdoc#84]
Currently, unittest do not check migration state, which could cause many issue.

**Comment by MagicTearsAsunder** [comment]
Probably a good idea is to use sqlite (or any different approach for a separate db dedicated specifically for tests)

[hint](https://github.com/epam/badgerdoc/blob/develop/annotation/tests/conftest.py#L193)

**Comment by andrejshulaev** [comment]
@MagicTearsAsunder the idea here is that we have to run tests other the same DB which we use for running application. Since we use different tool for producing and applying migrations (not like Django migrations), we have to make sure our tests runs in the same environment.

**Comment by spiridonovfed** [comment]
- [ ] Annotation
- [ ] .................... to be continued

**Comment by spiridonovfed** [comment]
PR: https://github.com/epam/badgerdoc/pull/129

**Comment by spiridonovfed** [comment]
PR: https://github.com/epam/badgerdoc/pull/141
(for pipelines) - merged

**Comment by spiridonovfed** [comment]
PR: https://github.com/epam/badgerdoc/pull/152
(for processing)

**Comment by spiridonovfed** [comment]
PR: https://github.com/epam/badgerdoc/pull/159
(for taxonomy)
