### ISSUE TITLE
Bug in release 1.1.0 on Vertex env - minio.error.S3Error on 'users' in regular background task  "delete_file_after_7_days"

### ISSUE THREAD

**Issue by spiridonovfed** [epam/badgerdoc#92]
Logs:
15-Dec-22 08:00:00 - [ERROR] - apscheduler.executors.default - (base.py).run_job(131) - Job "delete_file_after_7_days (trigger: cron[hour='*/1'], next run at: 2022-12-15 09:00:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/users_filter/./src/utils.py", line 32, in delete_file_after_7_days
    buckets = client.list_buckets()
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 647, in list_buckets
    response = self._execute("GET")
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 406, in _execute
    return self._url_open(
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 389, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: AccessDenied, message: Access Denied, resource: None, request_id: QXH4MVJY89W8GZ7H, host_id: ycEdNmVAVIugBtDcgetRJKeavrMebpPdS2ykj2C5HoNDVLWTCOve7ozq0SbK2SvScie+Zw4KI5U=

**Comment by spiridonovfed** [comment]
Also there logs:
15-Dec-22 12:10:52 - [INFO] - uvicorn.error - (on.py).startup(45) - Waiting for application startup.
15-Dec-22 12:10:52 - [INFO] - apscheduler.scheduler - (base.py).add_job(444) - Adding job tentatively -- it will be properly scheduled when the scheduler starts
15-Dec-22 12:10:52 - [INFO] - apscheduler.scheduler - (base.py)._real_add_job(885) - Added job "delete_file_after_7_days" to job store "default"
15-Dec-22 12:10:52 - [INFO] - apscheduler.scheduler - (base.py).start(171) - Scheduler started
INFO:     Application startup complete.
15-Dec-22 12:10:52 - [INFO] - uvicorn.error - (on.py).startup(59) - Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
15-Dec-22 12:10:52 - [INFO] - uvicorn.error - (server.py)._log_started_message(217) - Uvicorn running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
15-Dec-22 12:13:08 - [INFO] - src.logger - (query.py).introspect_token(156) - Sending request to Keycloak url: http://bagerdoc-keycloack/auth/realms/master/protocol/openid-connect/token/introspect/ to get user_info
INFO:     100.120.37.66:40958 - "GET /api/v1/users/users/current_v2 HTTP/1.1" 200 OK
INFO:     100.120.37.66:33240 - "GET /api/v1/users/users/current_v2 HTTP/1.1" 401 Unauthorized
15-Dec-22 12:20:42 - [INFO] - src.logger - (query.py).introspect_token(156) - Sending request to Keycloak url: http://bagerdoc-keycloack/auth/realms/master/protocol/openid-connect/token/introspect/ to get user_info
INFO:     100.120.37.66:54874 - "GET /api/v1/users/users/current_v2 HTTP/1.1" 200 OK
INFO:     100.120.37.66:37556 - "POST /api/v1/users/refresh HTTP/1.1" 404 Not Found
INFO:     100.120.37.66:37562 - "POST /api/v1/users/refresh HTTP/1.1" 404 Not Found
INFO:     100.120.37.66:37570 - "POST /api/v1/users/refresh HTTP/1.1" 404 Not Found
15-Dec-22 12:24:16 - [INFO] - src.logger - (query.py).introspect_token(156) - Sending request to Keycloak url: http://bagerdoc-keycloack/auth/realms/master/protocol/openid-connect/token/introspect/ to get user_info
INFO:     100.120.37.66:49810 - "GET /api/v1/users/users/current_v2 HTTP/1.1" 200 OK
15-Dec-22 12:27:12 - [INFO] - src.logger - (query.py).introspect_token(156) - Sending request to Keycloak url: http://bagerdoc-keycloack/auth/realms/master/protocol/openid-connect/token/introspect/ to get user_info
INFO:     100.120.37.66:39304 - "GET /api/v1/users/users/current_v2 HTTP/1.1" 200 OK
15-Dec-22 12:28:01 - [INFO] - src.logger - (query.py).introspect_token(156) - Sending request to Keycloak url: http://bagerdoc-keycloack/auth/realms/master/protocol/openid-connect/token/introspect/ to get user_info
INFO:     100.120.37.66:42294 - "GET /api/v1/users/users/current_v2 HTTP/1.1" 200 OK

**Comment by cakeinsauce** [comment]
Might help: https://github.com/minio/minio/issues/11541#issuecomment-779849201

**Comment by spiridonovfed** [comment]
The root of the problem is this:
We have a background task - 'delete_file_after_7_days'. Function is trying to get a list of all buckets and delete outdated files from them. But in Vertex env IAM Service Role does not have a permission to see a list of all buckets. It can only interact with one specific bucket. Fuction's inner logic should be changed

**Comment by spiridonovfed** [comment]
We decided to turn this background task in case if env var S3_CREDENTIALS_PROVIDER=aws_iam

**Comment by spiridonovfed** [comment]
PR: https://github.com/epam/badgerdoc/pull/100

**Comment by spiridonovfed** [comment]
PR merged (https://github.com/epam/badgerdoc/pull/100)
