### ISSUE TITLE
Remove lru-dict dependency from annotation service

### ISSUE THREAD

**Issue by cakeinsauce** [epam/badgerdoc#936]
@djo753
Annotation service uses lru-dict = "1.2.0" dependency which implements dict like structure with LRU cache functionallity. We should remove it as this dependency not well maintained and from unknown developer.

A/C:

- [ ] lru-dict dependency is removed from poetry dependencies list
- [ ] annotation/annotation/tasks/services.py LRU dict cache usage is replaced with new implementation using built in python capabilities

DOD:
- [ ] lru-dict is removed
- [ ] code is covered with tests
- [ ] functionallity is tested manually with fully working badgerdoc

**Comment by djo753** [comment]
Will do!

**Comment by djo753** [comment]
Published a PR with the changes needed to cover this issue:
https://github.com/epam/badgerdoc/pull/940
