### ISSUE TITLE
Remove kafka from annotation microservice

### ISSUE THREAD

**Issue by cakeinsauce** [epam/badgerdoc#937]
Annotation microservice used to use kafka to orchestrate ML pipelines between multiple services. It was gradually removed from multiple places, but some leftovers are still there - they should be removed.

A/C:
- [ ] kafka-python dependency is removed from poetry dependencies
- [ ] Any mention or function/variable of kafka is removed from annotation service

DOD:
- [ ] Kafka is removed
- [ ] Code is covered with tests
- [ ] Badgerdoc is fully working without kafka

**Comment by UkiStefanovic** [comment]
I'm taking this issue

**Comment by cakeinsauce** [comment]
Finished
